version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      - .:/app

  frontend:
    build:
      context: ./cerdas-frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./cerdas-frontend:/app
      - /app/node_modules